"""Initial migration

Revision ID: 03b47374717e
Revises: 
Create Date: 2026-02-16 22:03:03.742723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b47374717e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('garbage_count', sa.Integer(), nullable=True),
    sa.Column('cleanliness_level', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processed_file_path', sa.String(length=500), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index('idx_detection_cleanliness', ['cleanliness_level'], unique=False)
        batch_op.create_index('idx_detection_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_detection_file_type', ['file_type'], unique=False)
        batch_op.create_index('idx_detection_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_alert_detection', ['detection_id'], unique=False)
        batch_op.create_index('idx_alert_sent', ['email_sent'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_sent')
        batch_op.drop_index('idx_alert_detection')
        batch_op.drop_index('idx_alert_created_at')

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_email_active')

    op.drop_table('users')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index('idx_detection_status')
        batch_op.drop_index('idx_detection_file_type')
        batch_op.drop_index('idx_detection_created_at')
        batch_op.drop_index('idx_detection_cleanliness')

    op.drop_table('detections')
    # ### end Alembic commands ###
